version: "3.9"
services:
  jenkins-blueocean:
    build: 
      context: .
      dockerfile: Dockerfile
    image: myjenkins-blueocean:2.332.3-1
    container_name: jenkins-blueocean
    restart: on-failure
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
  
  socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:
